FROM rust:1.69.0-bullseye as builder
WORKDIR /tmp/acars_oxide
# hadolint ignore=DL3008,DL3003,SC1091,DL3009
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev librtlsdr-dev
COPY . .

RUN cargo build --release
