FROM rust:1.71.1-bullseye as builder
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
WORKDIR /tmp/acars_oxide
# hadolint ignore=DL3008,DL3003,SC1091,DL3009
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends libzmq3-dev librtlsdr-dev
COPY . .

RUN cargo build --release

FROM scratch
COPY --from=builder /tmp/acars_oxide/target/release/acars-oxide /acars-oxide
